name: Bug Report Mobile
description: Create a report to help us improve
labels: [ "type: bug" ]
assignees: [ "makeevrserg"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: "Example: I tried to launch an application and the screen become green!"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Open application first time...
        2. See the screen now is green!
    validations:
      required: true

  - type: textarea
    id: expected_behaviour
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: "The app should've open hello world screen!"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Add debug logs
      placeholder: "Add debug logs"
    validations:
      required: false


  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      placeholder: "Forget to mention, I'v using custom fork which creating green screen at start!"
    validations:
      required: false


  - type: markdown
    attributes:
      value: |
        ## Thanks for taking the time to fill out this bug report!
