name: Bug Report
description: Create a report to help us improve
labels: [ "type: bug" ]
assignees: [ ]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: "Example: Archive tab is not working. When it's opened the gray screen appeared!"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Switch on...
        2. Press button '....'
        3. Wait for the moon phase
        4. It burns
    validations:
      required: true

  - type: textarea
    id: expected_behaviour
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: "I expect to see the archive screen"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Add debug logs
      placeholder: "Add debug logs"
    validations:
      required: false

  - type: textarea
    id: target
    attributes:
      label: Target
      description: Specify the target
      placeholder: "The target is mobile application itself"
    validations:
      required: true


  - type: textarea
    id: target
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      placeholder: "Also forgot to mention! The app is....."
    validations:
      required: false



  - type: markdown
    attributes:
      value: |
        ## Thanks for taking the time to fill out this bug report!
