blank_issues_enabled: false
contact_links:
  - name: Forum
    url: https://forum.flipperzero.one/c/mobile/14
    about: Official community forum
  - name: Website
    url: https://flipperzero.one/
    about: Official site of Flipper Devices
  - name: Discord
    url: https://flipperzero.one/discord
    about: Official Discord.com page of Flipper Devices