blank_issues_enabled: false
contact_links:
  - name: AstraInteractive WEB
    url: https://astrainteractive.ru/
    about: Official AstraInteractive website
  - name: EmpireProjekt WEB
    url: https://empireprojekt.ru/wiki
    about: Official EmpireProjekt website
  - name: AstraInteractive Discord
    url: https://discord.gg/8fEzV2TDS2
    about: Official Discord.com page of AstraInteractive
  - name: EmpireProjekt Discord
    url: https://discord.gg/Gwukdr8
    about: Official Discord.com page of EmpireProjekt
  - name: EmpireProjekt TG
    url: https://t.me/empiresmp
    about: Official Telegram page of EmpireProjekt