name: Feature/Enhancement request
description: Add a new feature or enhance the project
labels: [ "type: enhancement" ]
assignees: [ "makeevrserg"]
body:
  - type: checkboxes
    id: searched
    attributes:
      label: Terms
      options:
        - label: "I'm using the very latest version of this project"
          required: true
  - type: input
    id: discord_tag_id
    attributes:
      label: Discord tag (optional)
      description: How can we get in touch with you if we need more info?
      placeholder: ex. DiscordTag#0001
    validations:
      required: false          
  - type: textarea
    id: what-happened
    attributes:
      label: "Describe the solution you'd like"
      description: A clear and concise description of what you want.
      placeholder: "Example: I want the ender dragon to break blocks in half whet it fly. The block should also have physics."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      description: "May be you've seen other project where something similar has done?"
      label: "Describe alternatives you've considered"
      placeholder: "A clear and concise description of any alternative solutions or features you've considered."
    validations:
      required: true


  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      placeholder: "Also forgot to mention! This feature....."
    validations:
      required: false


  - type: markdown
    attributes:
      value: |
        ## Thanks for taking the time to fill out this Feature Request!
